[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/owengage/fastnbt.git"]
git = "https://github.com/owengage/fastnbt.git"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"