[package]
name = "wither-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
serde.workspace = true
serde_json.workspace = true

proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"
