[package]
name = "wither-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
wither-client = { path = "../wither-client" }

log.workspace = true
env_logger.workspace = true
tokio.workspace = true
uuid.workspace = true